### ISSUE TITLE
Patreon API is coming

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#109]
[Source](https://www.reddit.com/r/patreon/comments/3dhxns/does_anyone_know_if_a_patreon_api_exists_or_is_in/cujkzf0)
> Hey! Patreon engineer here. Our iOS and Android apps run on our API (and will be launched in ~1 to 1.5 months), as does every new feature we've written since March (new make-a-post, real-time comments, notifications, the subbable integration, the upcoming payments rewrite, etc.). It's for internal use only right now, but we plan to open up API key registration within the next few months.
> 
> However! When you say things like "logging in/linking accounts", you're primarily talking about OAuth. OAuth is the system used when you see stuff like "Log in with Twitter" on Medium.com etc. After a user clicks "log in with patreon" on your site, you'll be granted what can be thought of as a limited-scope API token. It only can make calls on behalf of that user (e.g., it can get their pledge amounts to you, but not some other user's pledge amounts), and it can only access limited set of our whole API (e.g., it can get pledge amounts, but not something like make-a-post).
> 
> I spun up an OAuth provider service for us over the last two days, and am looking for some creators to help me test out integrating it with their websites. PM me for more info if you want it! I'll almost certainly be targeting a wordpress plugin as the first client, but would love to hear from the community what else to build for / what features y'all would want it to have / etc.

Some stuff is working already. The equivalent of #64 with the new API:
```python
from lrrbot.main import bot
from common import utils
import json

LRR_PATREON_CAMPAIGN = 112364

@bot.command("patreon")
@utils.throttle()
def patreon(lrrbot, conn, event, respond_to):
	data = json.loads(utils.http_request("https://api.patreon.com/campaigns/%s" % LRR_PATREON_CAMPAIGN))
	data, included = data["data"], data["included"]
	
	next_goal = (None, float("inf"))
	for goal in data["links"]["goals"]["linkage"]:
		for obj in included:
			if obj["id"] == goal["id"] and obj["type"] == goal["type"]:
				if obj["amount"] > data["pledge_sum"] and obj["amount"] < next_goal[1]:
					next_goal = (obj["title"], obj["amount"])
				break
		else:
			# Goal data not included with the response.
			raise NotImplementedError
	if next_goal[0] is not None:
		next_goal = " Next goal \"{}\" at ${:,.0f}".format(next_goal[0], next_goal[1] / 100)
	else:
		next_goal = ""
	conn.privmsg(respond_to, "{} {} for a total of ${:,.2f} per month.".format(
		data["patron_count"],
		"patrons" if data["patron_count"] != 1 else "patron",
		data["pledge_sum"] / 100
	) + next_goal)
```

I don't know if using it is currently against their TOS.

**Comment by mrphlip** [comment]
Their [TOS](https://www.patreon.com/legal) hasn't changed yet, but I imagine it will once the API launches for real...
