### ISSUE TITLE
Whisper command status

### ISSUE THREAD

**Issue by d3fr0st** [mrphlip/lrrbot#110]
We could have the bot whisper the current status(ie. command on cool down, sub only commands) of command instead of notifying it in chat.

**Comment by mrphlip** [comment]
I think for commands on cool down it's good how it is - the commands that are just a simple "get this info" notify in whisper, the ones that have public results (stat increments, highlights, etc) notify publicly.

We do have to consider that some users can't receive whispers, if they're using an external IRC client... so whispers have to be only used for either things that it's OK if they're missed (like the cooldown notices for commands that used to just be throttled silently before we added whisper support) or things that are specifically requested (like `!status` and responding to whispered commands).

**Comment by d3fr0st** [comment]
I meant for stuff like non-sub trying to use !quote and it spits out "This command is for sub only". It clutters the chat and has really no point being global rather than whisper
