### ISSUE TITLE
Link spam 

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#114]
I see a lot of URL shorteners in the spam filter. Should LRRbot open links and if it ends up in G2A, time out who posted it? There must be something that does that already as I've seen countermeasures: 

```
why don't you put a bannerino for kappamine? lol (http://t.co/PAo1mBVNJU in case you don't know what it is lol)
```

After two HTTP redirects it uses Javascript to redirect to `https://www.g2a.com/goldmine`.

<hr>

The other group of spam I noticed is the virus spam. Examples:
* `BibleThump BibleThump t.co.ua/Screenshot461`
* `Boostmeister 2015 Kappa j.mp/image_150915`
* `Learn kids 9nl.es/Screenshot_140915A3 TTours DogFace`
* `A bit of fantasy <3 j.mp/image_23401`
* `steam crazy 9nl.es/IMG_14091536 TTours NotLikeThis`

The links redirect to a SCR file ([AV scanner report of the latest one](https://www.metascan-online.com/#!/results/file/2195b421b33c4990a43600bc68d94c92/regular)). This also needs following redirects to consistently detect.

**Comment by RebelliousUno** [comment]
Do all the links have multiple layers of redirects?  
I presume a regular bit.ly link will only give one level of redirect?
Perhaps a timeout at anything with too many levels of redirect will catch most things?

Do we have stats on the bad links that we're catching I'd hate to have to institute some more draconian levels of link timeouts

**Comment by andreasots** [comment]
> Do all the links have multiple layers of redirects?

Most have a single redirect.

> Perhaps a timeout at anything with too many levels of redirect will catch most things?

The "kappamine" example is the only one I've seen with multiple redirects. Others have a single redirect, except those which redirect to Dropbox, which has an additional redirect added by Dropbox.

> Do we have stats on the bad links that we're catching I'd hate to have to institute some more draconian levels of link timeouts

LRRbot doesn't keep spam stats so I sent the entire chat log through the spam filter.

spam rule | matches and deleted | matches but not deleted
---|---|---
have to watch this | 271 | 0
j.mp spam | 91 | 16
apo.af | 31 | 17
imgur spam links | 40 | 3
G2A Spam | 32 | 10
Link shorteners | 19 | 4
mtgbot | 7 | 15
Asian Chicks Spam | 11 | 8
No song requests | 5 | 12
box drawing or block elements | 6 | 11
"championship riven skin code" | 15 | 0
G2A referral | 5 | 9
RAF2 | 12 | 0
adfly links | 9 | 0
combining mark abuse | 6 | 3
us.af spam | 1 | 7
gyazo spam | 5 | 0
swastika | 0 | 5
goldmine | 2 | 2
codes4free | 2 | 1
9nl.es spam | 2 | 0
G2A Goldmine | 2 | 0
Po.gl Spam | 2 | 0
clownsong | 2 | 0
microartist | 2 | 0
topstreamers | 2 | 0
Screamer | 0 | 1
gamepts.com | 0 | 1
smitepromotions | 1 | 0
steampromo | 1 | 0
TinyLinks | 0 | 0
Vine spam | 0 | 0
feedeep | 0 | 0
porn spam - miss %(1)s | 0 | 0
porn spam - naked %(1)s | 0 | 0
steam-cards | 0 | 0
steamcode | 0 | 0

**Comment by d3fr0st** [comment]
Well the easiest way to do this would just be blocking all link by default, and adding a whisper command to the bot that permits users but that would be annoying in the long run...

**Comment by andreasots** [comment]
> Well the easiest way to do this would just be blocking all link by default, [...]

If LRRbot was doing that I'm sure that we'll very quickly be told to stop.

**Comment by d3fr0st** [comment]
Oh I know that was mostly intended as a last resort scenario if link spam ever gets too bad. Like twitch chat has an option to not let users post link and requires mods/higher permission to permit users individually. At which point we cou

**Comment by AdmiralMemo** [comment]
The spam is getting worse and more random. Need more help. I'm with d3fr0st here. Maybe block all links by default and Mods can add known good users on a case-by-case basis?

**Comment by RebelliousUno** [comment]
Thinknwe might be wanting to move to permit system here.  Give subs carte Blanche with links.  Make none subs request links with a !permit

**Comment by andreasots** [comment]
I'd like to get #116 merged before we try that. I know @mrphlip wants to test it first but if the spam is getting that bad I can just merge it.

**Comment by d3fr0st** [comment]
Yeah this is getting ridiculous. Though if @mrphlip wants to test #116 first before relying on the whitelist method I'm down for that though Paul and Graham have agreed that we could end up using it chat seems pretty alright with it too.

**Comment by AdmiralMemo** [comment]
I also recommend that we tell people to use the !permit command even if they're subbed, as their sub could run out, but !permit won't.

**Comment by andreasots** [comment]
I think I'm missing half a conversation and would rather not dig through an active chat to find out.

I'll merge #116 some time after Beej has done streaming.

**Comment by d3fr0st** [comment]
Example spam from today "eqffukc. ewfer. wn. gydotf. [LINK]. iifarlt. jswq." Which is making almost impossible to create a spam rule for as it's different every bloody time

**Comment by andreasots** [comment]
There's a common element, the link. From what I've seen they seem to redirect to a small number of hosts. The couple I saw in the chat just now redirected to raf2.com then to either articles4daily.com or 2readarticles.com. That can be detected with #116.

**Comment by andreasots** [comment]
Merged #116, removed link shorteners from the spam filter.

**Comment by andreasots** [comment]
People aren't demanding LRRbot to be turned into thought police, closing.

**Comment by kaleb904** [comment]
Suggestion:
Would it be possible to check user data and determine if they have sent a message to that channel before and when the account was registered to determine if it's a potential bot or not? once determined that is indeed a banned link, you can forego the warning part and go straight to a full ban (possibly if the API allows reporting the user at that point, that could be added).
