### ISSUE TITLE
Twitch Subscriber tier level

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#1189]
Does LRRbot track the _tier_ of a Twitch subscriber? ie. whether people pay $5, $10, or $25 for their subscription. If not, could it do that?

I don't think there are many people who subscribe at a higher level, especially since we don't actually give them anything extra, but I believe there are a few and it might be nice to be able to highlight them on the sub scroll

**Comment by mrphlip** [comment]
@paul-lrr I've added the tier level to the API events: cf [the docs](https://github.com/mrphlip/lrrbot/commit/8cd6e3a268995ee517cfa9de5757230cca00e273#diff-a8dbd298c06672519991f7b5e8abde2847e86b34a4083e64069214a497787261).

I haven't changed anything from how LRRbot itself responds, so in chat or on the notifications page it'll look the same, but the data's there in the backend now if you want to use it.

**Comment by paul-lrr** [comment]
that's perfect, thanks!
