### ISSUE TITLE
Death Icon Change Suggestion

### ISSUE THREAD

**Issue by AdmiralMemo** [mrphlip/lrrbot#120]
While the lrrAWW icon is awesome, it's currently not working: http://static-cdn.jtvnw.net/emoticons/v1/2848/1.0
Thus, for the Death messages in Chat, it's kind of bleh right now.

I was thinking that, either temporarily or permanently, change it to a skull icon. (I also think the skull icon would be more appropriate, but that's personal opinion.)

Twitch has 2 public ones, a black one and a colored one:

SMSkull: http://static-cdn.jtvnw.net/emoticons/v1/51/1.0

KZskull: http://static-cdn.jtvnw.net/emoticons/v1/5253/1.0

**Comment by mrphlip** [comment]
Weird, lrrAWW is one of the ones that's working for me... at my end, lrrFRUMP is the one that's broken. Effing CDNs, how do they work?

I've changed it, but I kinda like the spirit of using the LRR-specific emotes when possible, so whenever Twitch manages to whip its CDN back into submission, I still want to switch it back. Or maybe lrrEFF makes more sense?

**Comment by AdmiralMemo** [comment]
Yeah, maybe? It's difficult, as different deaths come with different emotions. Some are angry, some are sad, some are scared, some are just indifferent. That's why I wanted to genericize it a little with one of the skulls, to match the on-screen overlay.

But, it's just a suggestion, as mentioned. I also like using the LRR-specific emotes...

Which ones are used now for each message, by the way? Maybe we can move some around, since I'm pretty sure they've gotten new emotes since the bot started. I don't know if you've been updating that, though.

**Comment by mrphlip** [comment]
* `!busstop` = :-/
* `!completed` = lrrAWESOME
* `!death` = SMSkull
* `!diamond` = PunchTrees
* `!flunge` = no emote
* `!pardonfuck` = lrrEFF
* `!pave` = lrrCOW
* `!russell` = no emote (used to be 🐦 but that started causing problems - #84)
* `!scream` = lrrEFF (again)
* `!tilt` = lrrEFF (again (again))

Some of those lrrEFFs could probably be changed...

**Comment by AdmiralMemo** [comment]
Pardonfuck could use ItsBoshyTime maybe? It's a yellow triangle with an exclamation mark. Another alternative could be the O_o emote. Or, if you want to a LRR-related emote, lrrFINE maybe? (Actually, lrrFINE could be used to cover both meanings of the counter, if you think about it.)

Yes, diamond, pave, and tilt are great as they are. Busstop is busstop.

Completed is fine if you want to keep it, but consider the alternatives of lrrHORN and lrrGOAT as well. If you think lrrAWESOME is better than those, that's fine as well. :-)

Flunge could be lrrHAM since that's kind of appropriate. "Flunging" and "Going Ham" mean roughly the same thing.

We can go back to lrrAWW for deaths when Twitch gets its act together.

I know that each person has a different list of what works or not, but just for reference, here's the list of emotes that don't work for me, for the time being:

:-P
FrankerZ
HeyGuys
RalpherZ
RitzMitz
SeemsGood
shazamicon
lrrAWW
lrrEFF
lrrFRUMP

**Comment by kaleb904** [comment]
Does this current bug with the broken emotes necessitate a change? If it's a known problem that they are "working" on, should it still be done? Or is this more of a "we should do this anyway" kind of change?

**Comment by d3fr0st** [comment]
Honestly broken emotes are inconsistently broken nothing we can really do other than removing emotes all together. As for lrrEFF being overused we'll get to it at some point... I know Graham has talked about adding more emotes, so we'll see I guess

**Comment by AdmiralMemo** [comment]
Actually, I wonder if scream should be lrrSPOOP instead of lrrEFF. Just a suggestion.

**Comment by ka13b** [comment]
It would depend on the nature of the scream. lrrSPOOP would be a scared scream, whereas lrrEFF would be an angry/frustrated scream (I think).

**Comment by mrphlip** [comment]
So, I can currently see all the LRR twitch emotes from here. Am I just lucky, or are the CDN issues fixed?

**Comment by ka13b** [comment]
It seems the CDN issue might be resolved. I have been able to see emotes that I previously could not for a while now.

**Comment by AdmiralMemo** [comment]
Yeah, it looks resolved if you want to change anything back.
