### ISSUE TITLE
Patreon can has API now

### ISSUE THREAD

**Issue by mrphlip** [mrphlip/lrrbot#125]
https://patreon.zendesk.com/hc/en-us/articles/206525646-Does-Patreon-have-an-API-

Looks limited (and I think we'd need to get an oauth key from LRR??? the documentation seems... light) but maybe we could do a thing with this? We'd at least be able to get the "total amount pledged" that pump19 currently does, and maybe we could do something with that web hook to make it so new patrons get the same treatment as new twitch subs? Have to see if that's something LRR even wants.

**Comment by d3fr0st** [comment]
Do we even need to integrate this? Like a couple of features such as the new patron notifications would be nice. But pump19 really handles most of this (yes using proper API would be good but be nice) but pump19 also has a couple of features other than the patreon which would suck to lose (rdio, codefall, lrr minecraft server integration) and at that point we'd be integrating redundant features...

**Comment by andreasots** [comment]
> Do we even need to integrate this?

I at least want to treat patrons as subscribers for the purposes of sub-only commands.

**Comment by d3fr0st** [comment]
Yeah that would be awesome for sure but my concerns are mostly with pump19 existing commands like "total amount pledged".

**Comment by mrphlip** [comment]
Hmm, we'd need a way for users to link their patreon accout to their twitch account name via lrrbot (which is, at least, supposed to be one of the things that patreon API supports)... then track that mapping.

And this wouldn't be the first time we migrated commands that originated in pump19 over to lrrbot (I'm looking at you, quotes page)... the only reason that we hadn't done it before now was the lack of an API.

**Comment by d3fr0st** [comment]
True, though how about talk with twisted pear and migrate the whole thing at this point since the whole scrubbing patreon won't be a necessity soon hopefully...

**Comment by andreasots** [comment]
cc @pyrige

**Comment by pyrige** [comment]
I'm not too fond of the idea of stripping Pump19 down further, but adding Patreon support to LRRbot is probably a decent enough idea, especially if you manage to link patrons to their Twitch accounts.
