### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#127]
I got a TLS certificate from [Let's Encrypt](https://letsencrypt.org/) for everything I run on my server, including LRRbot. 

# Windows XP

I tested my server setup on various browsers:

Browser | OS | Result
----------|----|----
Firefox 42 | Windows Server 2012 | OK
Chrome 47 | Windows Server 2012 | OK
IE 6 | Windows XP SP3 | Certificate error
IE 8 | Windows XP SP3 | Certificate error
IE 8 | Windows Vista SP2 | OK
Chrome 47 | Windows XP SP3 | Certificate error
Firefox 42 | Windows XP SP3 | OK

So it works on anything that isn't Windows XP. Do we care about Windows XP support? I want to say no, because a) it's not supported by Microsoft anymore, and b) [Chrome will be dropping Windows XP support soon](http://chrome.blogspot.com.ee/2015/11/updates-to-chrome-platform-support.html) so the only browser that isn't full of holes on that OS will be Firefox and Firefox works fine.

# Mixed content warnings

The images we use from Twitch (profile pictures, emotes, VOD thumbnails) are over HTTP. Since Twitch's CDN supports HTTPS, some well-placed `str.replace` calls should fix this.

**Comment by mrphlip** [comment]
Would it be tricky to detect if the User-Agent contains `Windows NT 5`, and if it does, not redirect to HTTPS? Just a thought...

If that's at all complicated, I'm OK with not supporting XP.

**Comment by andreasots** [comment]
No XP support then. Nginx's [`if`](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#if) doesn't support boolean operations so I can't do something like 'if over HTTP and user agent doesn't match `Windows (NT 5|XP)` then redirect to HTTPS' because there is no 'and' and the `if`s can't be nested to emulate one.
