### ISSUE TITLE
Mixed content error again

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#137]
Now https://www-cdn.jtvnw.net/swflibs/TwitchPlayer.swf redirects to 
http://www-cdn.jtvnw.net/swflibs/TwitchPlayer.rfc07d37fc4eed1d17243b452dd3441665496e1e0.swf which then gets blocked as mixed active content.

Twitch pls
pls

**Comment by mrphlip** [comment]
(pls)

**Comment by d3fr0st** [comment]
Did I ever mentioned how glad I am you guys are handling this? I have literally no idea what any of this means...
