### ISSUE TITLE
twitch raid event

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#1435]
I feel like I may have asked about this before, but maybe on the slack and it got eaten by the 90 day limit: Is LRRbot currently set up to handle raids? I see that there is a `twitch-raid` key in the `https://lrrbot.com/api/v2/stormcount` endpoint but I don't see any `twitch-raid` events in the event stream (even going back 30 days). Just thinking about integrating a raid notification into the existing notifier widget

**Comment by andreasots** [comment]
Yes but it has a bug that prevents it from working (potentially fixed in cd17f2a88fdc2df2653f9364d6d70e21a40801a2, not deployed because the stream is live).

**Comment by andreasots** [comment]
Raid notifications should be fixed now.

**Comment by andreasots** [comment]
Raid notifications are fixed:
```console
$ curl -s "https://lrrbot.com/api/v2/events?last-event-id=367180" -H "Accept: application/json" | jq .events[0]
{
  "id": 367181,
  "event": "twitch-raid",
  "data": {
    "name": "BoozyP",
    "count": 4,
    "login": "boozyp",
    "avatar": "https://static-cdn.jtvnw.net/jtv_user_pictures/701f2a69-6d86-4990-97e7-071ed49f2cba-profile_image-70x70.png",
    "time": "2023-03-18T05:02:04.466562+01:00"
  }
}
```

**Comment by paul-lrr** [comment]
Awesome, thanks!
