### ISSUE TITLE
twitch chat replay

### ISSUE THREAD

**Issue by d3fr0st** [mrphlip/lrrbot#145]
http://blog.twitch.tv/2016/02/introducing-chat-replay/ so this is a thing now, it doesn't work on old stream but it will make that lrrbot functionality obsolete.

**Comment by mrphlip** [comment]
Interesting.

I think we should keep the chatlog code in lrrbot, though... no sense in ripping it out unless it's actually costing us something, and I still have hope we'll be able to sync the chat to the YouTube uploads at some point.

The ability for chat mods to purge messages from the log, though, is a good feature, and maybe that'd be worth adding to our version...

**Comment by mrphlip** [comment]
The ability to purge messages from the log has been spun off as its own item: #151
