### ISSUE TITLE
patreon oauth2 gets 500 error from lrrbot.com

### ISSUE THREAD

**Issue by rakslice** [mrphlip/lrrbot#1485]
The https://lrrbot.com/patreon/ url suggested in the help under !patreonbot to connect my twitch user with patreon in lrrbot is able to authorize to twitch ok but in the patreon authorization flow directs me to the patreon site okay and i click the button to authorize it, but the redirect back to `https://lrrbot.com/patreon/login?code={some stuff}&state={more stuff}` fails with a generic "500 Internal Server Error" page.

**Comment by andreasots** [comment]
A Patreon account can be connected to a single Twitch account and your Patreon account was already connected to another Twitch account (delta__vee).

I've changed it so that before linking the accounts it will unlink it Patreon account from any other Twitch accounts.
