### ISSUE TITLE
Chat servers are going to migrate to AWS EC2 servers

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#149]
[PSA: Chat servers are going to migrate to AWS EC2 servers](https://discuss.dev.twitch.tv/t/psa-chat-servers-are-going-to-migrate-to-aws-ec2-servers/4877)
> We've spent considerable amount of time over the last half year preparing to migrate our chat system to AWS EC2 servers. We're finally ready to start the transition (and identify any misconfigurations / new scaling concerns in the new environment).

> [...]

> Our current rollout plans are as follows:

>  * Migrate channels one-by-one on a whitelist basis, partners / staff who opt-in to the risks of using the new cluster
>  * As our confidence increases that things are working correctly, slowly add more Twitch partners to the whitelist
>  * Once all Twitch partners are on the whitelist, transition all channels to use the new servers

> Currently, in order to determine what cluster and servers to connect to, you can use http://tmi.twitch.tv/servers?channel=brildum. You'll notice that it returns that my channel's cluster == "aws" and the servers list no longer uses IP, but DNS: "irc.chat.twitch.tv" (for raw tcp) and "irc-ws.chat.twitch.tv" (for websockets).

> [...]

> Other items of interest:
> - irc.chat.twitch.tv supports 80, 6667 (no SSL) and 443, 6697 (SSL)
> - irc-ws.chat.twitch.tv supports 80 (no SSL) and 443 (SSL)
> - These changes do not affect group chat

**Comment by mrphlip** [comment]
My opinion is that adding code to call this `/servers` call would be overkill, as it sounds like it's only going to change once, or at least that's the plan... we can just change `hostname` in lrrbot.conf when that happens.

SSL support will be nice, though.

**Comment by mrphlip** [comment]
This changeover happened. We're now connecting to `irc.chat.twitch.tv` on port 6697, using SSL.
