### ISSUE TITLE
500 Internal Server Error after OAuth2 when linking Patreon account

### ISSUE THREAD

**Issue by creideiki** [mrphlip/lrrbot#1531]
I'm trying to link my Patreon and Twitch accounts with LRRBot. I go to https://lrrbot.com/patreon/ and click "Link Patreon account". I get redirected to an OAuth2 transaction on Patreon saying that LRRbot wants to view my account and pledge information. I click "Allow". I get redirected back to `https://lrrbot.com/patreon/login?code=<>&state=<>`, which shows an "Internal Server Error" message.

These are the same symptoms as in #1485, but I've never had another Twitch or Patreon account, so I don't think it's the same root cause.

**Comment by andreasots** [comment]
This is now fixed. You should be able to link the accounts now.

**Comment by creideiki** [comment]
Yes, it works now. Thanks!
