### ISSUE TITLE
Parens part of the URL again

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#163]
![twitch-pls](https://cloud.githubusercontent.com/assets/104879/13858620/1d88362c-ec88-11e5-9147-90590cc25c37.png)

**Comment by andreasots** [comment]
This time instead of U+200B ZERO-WIDTH SPACE let's try U+200A HAIR SPACE. I only checked how it behaves on Twitch and with Jinja's `urlizer` and it seems to work. It's looks like (https://lrrbot.mrphlip.com ). U+200A isn't as thin as U+200B but is a lot better than U+0020.

**Comment by mrphlip** [comment]
It's kinda funny having this and #150 open at the same time...

I think we should have some sort of global constant and/or config setting for this... make everything `"(%s%s)" % (url, spacing_char)` so we can more easily change it from a ZWSP to an empty string whenever Twitch changes its mind about URL parsing.

(Personally this means more time with the links being broken in xchat, as it doesn't recognise Unicode spaces and parses them as part of the URL, but it's more important we get it working in the real Twitch chat than in random IRC clients...)

**Comment by andreasots** [comment]
> Incidentally: Why hair space over ZWSP?

```python
>>> jinja2.utils.urlize("(http://lrrbot.mrphlip.com\u200B)")
'(<a href="http://lrrbot.mrphlip.com\u200b">http://lrrbot.mrphlip.com\u200b</a>)'
>>> jinja2.utils.urlize("(http://lrrbot.mrphlip.com\u200A)")
'(<a href="http://lrrbot.mrphlip.com">http://lrrbot.mrphlip.com</a>\u200a)'
```

**Comment by andreasots** [comment]
Twitch is so helpful and converts all whitespace characters to a regular space. (ZWSP isn't actually whitespace.)

(╯°Д°）╯︵ɥɔʇıʍʇ

Change our `urlize` to recognise ZWSP and use that?

**Comment by mrphlip** [comment]
> Change our `urlize` to recognise ZWSP and use that?

Should be easy enough. Not tested, but something like:
```py
import jinja2.utils
jinja2.utils._word_split_re = re.compile(r'([\s\u200b]+)')
```
should work as a monkey-patch.
