### ISSUE TITLE
Codefall page

### ISSUE THREAD

**Issue by mrphlip** [mrphlip/lrrbot#17]
To make sharing of steam/etc codes possible without bots sniping the codes out of the chat, we should have a page on the website that allows users to post codes, and other users to see them, but only if they're signed in to the site.

Implementation thoughts:
A way to mark individual codes as "claimed" (including a way to say "I got this") would be useful to clear out the older codes. When a new code is added, the bot should announce it in the chat (with throttle, naturally) and it should get SSEd out to anyone who has the page open, so everyone has a chance to see it.

**Comment by AdmiralMemo** [comment]
Pump19 currently allows this.
