### ISSUE TITLE
!game refresh does nothing?

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#180]

**Comment by d3fr0st** [comment]
Is it the bot or is it twitch API messing up?

**Comment by andreasots** [comment]
The API was returning correct info. I looked at the code and `!game refresh` isn't flushing the cache on `common.twitch.get_info` and flushing the cache on `common.twitch.get_game` which I think does nothing.

**Comment by andreasots** [comment]
Regressed after #185.
