### ISSUE TITLE
Disabled whispers

### ISSUE THREAD

**Issue by mrphlip** [mrphlip/lrrbot#182]
It couldn't find the group chat server for some reason, so I've disabled whispers for the moment until one of us has a chance to actually debug it properly

**Comment by andreasots** [comment]
[[PSA] Group Chat is migrating to AWS servers](https://discuss.dev.twitch.tv/t/psa-group-chat-is-migrating-to-aws-servers/5618)
> Hey everyone,
>
> Group chat will be moving to AWS this week. The migration will be mostly transparent on your end, but you'll want to make sure you're connecting to the group chat servers from this API:
> 
> http://tmi.twitch.tv/servers?cluster=group
>
> When the migration is done, Group Chat will use the same servers as our main IRC chat!
> 
> The group.tmi.twitch.tv DNS record will point to irc.chat.twitch.tv when the migration is done. I recommend using the API for group servers, as the port mappings may change during the migration. For example, port 443 is only used for secure (SSL) connections in the new environment.
>
> I'll update this topic during the migration.
