### ISSUE TITLE
Show IDs are counting up without new shows being added

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#197]
I added an entry for AFK and it got 439 as the ID instead of 22.

**Comment by mrphlip** [comment]
Possible the "insert on conflict update" in `set_show` is incrementing the generator? Would be my first guess.

That said... is this a problem?

**Comment by andreasots** [comment]
Because the ID is a 31 bit integer I was slightly worried about overflows. At the current rate it will overflow in 200k years so it's not actually a problem.
