### ISSUE TITLE
Card recognizer changes

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#203]
I have developed a system to automatically generate a recognition database from a tappedout.net deck list. This will allow us to use the card recognizer for highlander games or other situations when you have cards from many different sets (like the upcoming grab bag draft). Unfortunately, due to a bunch of really annoying inconsistencies in set and card naming systems, the process is more compicated then it should be :/ 
The end result is a system that seems to work well, but might be harder for lrrbot to parse. The cards will be sent to LRRbot with the set code and the full card name in the format `<set code>_<URL encoded card name>.jpg`. The set codes are from magiccards.info and I'm using the card name instead of the multiverse id or number because that is how tappedout exports its deck lists and since mtg card names are unique, I can just search the card name to quickly get every printing of a particular card, even promos, special editions or other versions that aren't in Gatherer and don't have multiverse ids. I hope this format isn't going to cause trouble for LRRbot, but if it does, I'm open to suggestions for how to make it easier.

**Comment by andreasots** [comment]
How about just the unencoded card name? As you say, the card name is unique.

Are the other formats (multiverse ID, set code and collector number) be ever used again?

**Comment by mrphlip** [comment]
Well, I'm guessing it's just easier to send the same filenames to us that they're sending to the overlay. And I imagine they still want the set code in there for the overlay, make sure they're showing the right art for cards... especially when they're using the scanner for old packs opened on TTC, they'd want the art from that set, not whatever the most recent printing is.

**Comment by paul-lrr** [comment]
Mrphlip is correct in that we need the set code for the overlay to make sure we are showing the correct version of the card. I am currently sending you the file name from the overlay, but it would be straight forward to manipulate the string before I send it. Would it be helpful if I just sent the unencoded name?
We shouldn't need to use the set code + collector number format again, but the old card recognizer is still useful for situations where we are only looking at cards from a couple of sets, so you should expect the gatherer urls with multiverse ids to still come through.
