### ISSUE TITLE
EMN preprerelease card names

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#225]
I know I have gone back and forth on the formatting of card names for the recognizer, but for the EMN preprerelease would you prefer the cards were sent as the card numbers or the names? It doesn't matter for the overlay system, so whatever is easier for lrrbot is fine with me.

**Comment by andreasots** [comment]
The easiest would be the current current format which is set name and card name separated by either a dash or an underscore.

**Comment by paul-lrr** [comment]
ok, cool! One small wrinkle is with the new **Meld** cards, I am making the system register either half of the double cards as the full combined card. Eg. The backside of _Hanweir Garrison_ and _Hanweir Battlements_ will both recognize as _Hanweir, the Writhing Township_ (or `EMN_Hanweir%2C%20the%20Writhing%20Township.jpg`) which will be an image of the two card together

**Comment by mrphlip** [comment]
That reminds me, I'll need to figure out a good way to show Meld cards in chat, and I'll need to update the mtgsalvation scraper, and the mtgjson parser once they update. Posting mostly to remind myself to do it.
