### ISSUE TITLE
Styles and scripts get cached

### ISSUE THREAD

**Issue by mrphlip** [mrphlip/lrrbot#254]
Whenever we update the JS or CSS files for the site, browsers still keep using the old cached versions.

Is there some setting in Flask/nginx to make it better insist on the new file whenever it changes?

Or if not, can we make it so the URI changes every update? Say, have the webserver run `git rev-parse HEAD` on startup, and make the `script` and `style` tags point to `static/style.css?rv=abc123` or whatever. Ideally something that's going to change automatically whenever we update, not something we have to change manually whenever we change the scripts.

**Comment by tessereth** [comment]
An asset pipeline is probably what your after. You can always roll your own if you like but a token amount of googling suggests [flask-assets](https://flask-assets.readthedocs.io/en/latest/), a wrapper around [webassets](https://webassets.readthedocs.io/en/latest/index.html), which automatically [handles cache expiry](https://webassets.readthedocs.io/en/latest/expiring.html).

**Comment by mrphlip** [comment]
That looks ideal to me... just need to get it set up, I guess.
