### ISSUE TITLE
Sub Slideshow testing

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#259]
Not sure if this should be a new "issue" but I'm trying to do some adjustments on the sub slide show that we play at the end of streams and figure out why it sometimes glitches out. I'm pretty sure lrrbot is fine and it is an issue with my script, but the problem is that is it always works fine during tests and only messes up during the actual broadcast 😓. I'm assuming that it has something to do with handling the flood of new subs that happen while the slideshow is going but that is very difficult to test. Is there some way I can send fake/test sub notices so that I can figure out what is happening in a controlled system (I'll make sure not so do it during any actual streams)? Failing that, is there a better way to debug this without having to time the debugging to when we're are doing real sub welcomes?

Cheers,
Paul

**Comment by andreasots** [comment]
> Is there some way I can send fake/test sub notices [...]?

No and I think it's not a good idea as it makes the code more complex for basically no reason.

You could try running the [server-sent events server](https://github.com/mrphlip/lrrbot/blob/a7928452422862546b20bcec3aa632de302f3a50/eventserver.py) locally. It needs Postgres for storing old events but I know from past experience that it's difficult to set up on Windows. To make it run without Postgres replace lines 115-121 with `id = 1` and remove lines 47-63, 25 and 6. These line numbers refer to the lines in the original file.

To send events to the server you can use something like this:

```python
import asyncio
import common.rpc
import datetime
import pytz

async def main():
    await common.rpc.eventserver.event('twitch-subscriber', {
        'name': 'LRRbot',
        'count': 1,
    }, datetime.datetime.now(tz=pytz.utc))
    await common.rpc.eventserver.close()

asyncio.get_event_loop().run_until_complete(main())
```

If this proves to be too difficult I can write you a standalone GUI based thing instead.

**Comment by paul-lrr** [comment]
Interesting! I will give that a shot, thanks

**Comment by mrphlip** [comment]
Looks like everything is back to working, I haven't seen the sub slideshow fail since this item, so I'm closing it.
