### ISSUE TITLE
Integrate MTGBot features

### ISSUE THREAD

**Issue by danbopes** [mrphlip/lrrbot#260]
Hey guys,

I've just integrated a WebAPI into MTGBot. It will allow you to basically proxy commands from MTGBot into your bot (Which should be helpful to add functionality that MTGBot currently has, like the !record command). To access the API, simply direct a GET request here:

http://mtgbot.tv/api/chatapi

The only parameter is command, which is the chat message to parse/output. For example:

http://mtgbot.tv/api/chatapi?command=!record%20numotthenummy

Which will result in:

```
{
    status: "success",
    message: "NumotTheNummy is currently sideboarding for game 2 in a Modern Cube Single Elimination Phantom Draft (Round: 3). Current Record: 2-0. (Up a game)"
}
```

All commands are executed in a non-mod/non-owner context, which means that non user commands will not work. All user commands should work normally, like '!ecard/!dcard/!card/!flavor'...etc. All I ask is a shout out on the commands page to mtgbot.tv for the commands that link to MTGBot.

**Comment by andreasots** [comment]
There doesn't seem to be any commands we'd like to have except for maybe `!record` but that should be already on screen. Will keep this in mind for the future though.
