### ISSUE TITLE
Sawn-off LRRbot for Discord

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#261]
I want a limited version of LRRbot for the official LRR Discord server.

Features I want:
 * [ ] A `!timeout` command that adds a role to a user that prohibits them from talking and later removes that role.
 * [x] Autoupdating topic for `#general` that would say what `!status` does in LRRbot.

These I'm slightly worried about:
 * ~~~`!card` for `#magic`.~~~
 * ~~~Then also something for `#pokemon`?~~~
 * [ ] `!nextfan`. I think we don't need `!next` because of the autoupdating topic for `#general`.
 * [x] `!live`
 * [ ] `!quote` and the associated commands.
 * [ ] `!advice` and other static commands.
 * [ ] Also `!explain`?

The concern for those is because unlike Twitch chat Discord is persistent and so spammy commands are more of an issue. Perhaps we could delete the responses after a certain period. Maybe also the commands issued?

**Comment by RebelliousUno** [comment]
Certainly another bot I've used (https://github.com/Just-Some-Bots/MusicBot) can delete it's messages after a certain amount of time.  I don't know about deletingly other users commands though.  If the bot were more restricted in it's abilities and we were harder on the features then it becomes less spammy through not needing to be used


I'd just keep it to !timeout and the autoupdate and live
I'd not even bother including quote, or advice personally keep those restricted to twitch chat and keep the utility we actually /need/

**Comment by andreasots** [comment]
I've started working on this so I've turned the initial comment into a task list. I have a prototype of the autoupdating topic finished and I'm currently refactoring it into something that hopefully won't be a ball of spaghetti code.

The case for static commands isn't `!advice` but stuff like `!fanschedule` that contains useful information.

There was also this suggestion:
> RebelliousUno: Discord really needs a way to.do on demand channels
> RebelliousUno: That are temp
> RebelliousUno: We could implement this on a bot though
> RebelliousUno: With a command for a new voice channel. Bot creates the channel
> RebelliousUno: When it is empty for say 5 minutes the bot deletes it
> RebelliousUno: If i get some time.i might try to code this up this weekend can't be that hard right?

**Comment by mrphlip** [comment]
I wonder if there's cause to refactor the whole command-processing stuff out into its own module, independent of the irc code... have some sort of indirection layer that lets it receive commands and return responses without being tightly coupled to irc. Then the ircbot code and the discord bot could both call that.

Then potentially other interfaces could be added in the future (maybe the Twitter account could start listening to commands too?)...

Individual commands could have decorators (or parameters to `@command`), that say whether they can be used by the different interfaces... essentially extending the `@public_only` we already have.

No idea if this is a _good_ plan or not, but it's a thought.

**Comment by andreasots** [comment]
Discord LRRbot is now a [separate project](https://github.com/andreasots/eris).
