### ISSUE TITLE
LRRbot has been IP-banned from Discord

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#340]
```
Error 1006 Ray ID: 39f2d33dba8d63a3 • 2017-09-16 09:33:36 UTC
Access denied
What happened?

The owner of this website (discordapp.com) has banned your IP address (78.47.244.60).
```

**Comment by andreasots** [comment]
It also runs my mail server, my personal website and the rest of LRRbot and nothing else that I know of uses Discord on that server.

**Comment by andreasots** [comment]
Filed a support request.

**Comment by andreasots** [comment]
![Well, fuck.](https://media.discordapp.net/attachments/180419911636615168/358435011801907200/unknown.png)

I'm going to try Tor but most likely will hit Cloudflare's CAPTCHA wall.

**Comment by mrphlip** [comment]
Nice of them to provide ample warning time...

**Comment by andreasots** [comment]
No CAPTCHA wall for Discord but Google Calendar returns 403.

**Comment by andreasots** [comment]
Twenty minutes ago:
![screenshot_20170916_213837](https://user-images.githubusercontent.com/104879/30514915-73c9bb56-9b27-11e7-8cae-64b9cd6e0c54.png)

Will check it out after the PPR is over.

**Comment by andreasots** [comment]
It's working.
