### ISSUE TITLE
Chat quotes

### ISSUE THREAD

**Issue by VmKid** [mrphlip/lrrbot#40]
While the crew tends to have their funny moments, the chat can have their own witty moments.

So I'm suggesting a sort of Quote Database for the chat. They might be accessible from the LRRBot website, or with certain commands. For example:

```!addquote <INSERT FUNNY WORDS HERE> - Add a new quote to the database```
```!delquote <Quote Number> - (Mod Only?) Remove a quote from the database```
```!quote <Quote Number> - Reposts the selected quote. If no number is given, LRRBot will reply with a random quote.```
```!qdb - Links to the quote database.```

Any thoughts? I'd love to try and help make it, but I don't really know Python well enough. :frowning:

**Comment by AdmiralMemo** [comment]
We currently have that available on Pump19.
