### ISSUE TITLE
Unstable cards for recognizer

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#404]
So obviously Unstable is going to cause some problems for the recognizer and for the LRRbot connection. 
My current plan is to add some flags at the end of the filename (separated with an underscore) to help deal with cards that needed to be treated differently on the overlay. 
Those flags are:
_Alt Art_: `_<num>`
`UST_Amateur Auteur_1.jpg`
`UST_Amateur Auteur_2.jpg`

_Alt Text_: `_<letter>`
`UST_Very Cryptic Command_a.jpg`
`UST_Very Cryptic Command_b.jpg`
`UST_Very Cryptic Command_c.jpg`

_Token_: `_TKN`
`UST_Goat_TKN.jpg`
`UST_Beast_1_TKN.jpg`
`UST_Beast_2_TKN.jpg`
(some UST tokens have alt art)

_Host_: `_HOST`
`UST_Voracious Vacuum_HOST.jpg`
`UST_Ordinary Pony_HOST.jpg`

_Augment_: `_AUG`
`UST_Ninja_AUG.jpg`
`UST_Monkey-_AUG.jpg`

The combined Augment/host creature will be sent through as
`UST_Ninja_AUG+UST_Voracious Vacuum_HOST.jpg`

Do you think this will be a problem for LRRbot? My hope is that by Friday, all of the alt text cards will be spoiled and we can have consensus about which is the "A" version, the "B" version, etc

Also as a warning, some cards in Unstable use characters that are not usually in MtG card names. Hopefully cards like `UST_Dr. Julius Jumblemorph.jpg` and `UST_Hazmat Suit (Used).jpg` won't cause problems for LRRBot.

Would it be easier if I just sent the card name to LRRBot, instead of the full url? eg. send `UST_Amateur Auteur_1` instead of `http://localhost/cards/UST_Amateur Auteur_1.jpg`

**Comment by andreasots** [comment]
> alt art / alt text

I'd like to use the [official variant scheme](https://magic.wizards.com/en/articles/archive/news/unstable-variants-2017-12-06) if possible. It looks like MTGJSON is also looking into the variants (mtgjson/mtgjson#510) and I hope they release a new version before the PPR.

> Also as a warning, some cards in Unstable use characters that are not usually in MtG card names. Hopefully cards like `UST_Dr. Julius Jumblemorph.jpg` and `UST_Hazmat Suit (Used).jpg` won't cause problems for LRRBot.

They don't.

> Would it be easier if I just sent the card name to LRRBot, instead of the full url? eg. send `UST_Amateur Auteur_1` instead of `http://localhost/cards/UST_Amateur Auteur_1.jpg`

Not really. Currently we decide between formats (multiverse ID or card name) based on the hostname of the URL. If you want we can change formats but maybe not two days before a PPR.

**Comment by paul-lrr** [comment]
Ok, ya. The official variant scheme is the way to go. I was afraid that WotC wouldn't "officially" acknowledge the variants until after the release. 

So, I guess the alt art variants will also use the a,b, c system instead of numbers (I was doing them differently in my system because they have to be handled differently by the recognizer). I will make sure that my abc's lines up with the official list in that WotC article

**Comment by mrphlip** [comment]
OK, things that should now work:
* `UST_Very Cryptic Command_A.jpg` et al, for everything in that dailymtg article. (NB: capital/lowercase a/b/c doesn't matter.)
* `UST_Adorable Kitten_HOST.jpg` and `UST_Ninja_AUG.jpg` which will display the same thing as without the suffix (but the cardviewer will still consider the ones with the suffix and without to be different cards, per #379, so please only do one or the other)
* `UST_Ninja_AUG+UST_Adorable Kitten_HOST.jpg` which will display the combined "Ninja Kitten" text (NB: aug has to be first and host second)

Tokens, I haven't included. There are one or two somewhat complicated ones, but for the most part it all looks pretty simple, I don't think we need them.

There are already [parens](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74275) in Magic, and [dots](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=114921) are even in black-border, so the card db handles those already. Unstable didn't provide anything new in that recard.

**Comment by mrphlip** [comment]
Leaving this item open for when mtgjson inevitably has all these variants in their own db, and we can rework somehow to use that instead.

**Comment by mrphlip** [comment]
A thought: do we want to have some sort of indication when someone types `!card Very Cryptic Command` or w/e that the text returned isn't necessarily the correct text, as there are variants?

**Comment by mrphlip** [comment]
Closing since the PPR is over and everything went well
