### ISSUE TITLE
(yet another) card recognizer input format

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#425]
We have started to use scryfall.com more and more for card images because a) the images are super high res and b) they have a very powerful, complete and well documented API. I believe LRRbot already knows about the multiverseid-style scryfall urls (`https://api.scryfall.com/cards/multiverse/<multiverse id>'?format=image`) but I'm thinking about accessing images using their default format which is based on the set code and card number. This means that some card urls would be sent in the following format:

Alpha Fireball:
`https://img.scryfall.com/cards/large/en/lea/149.jpg?1509809953`
Zendikar Expeditions Stripmine:
`https://img.scryfall.com/cards/large/en/exp/43.jpg?1509690533`
Antiquities Stripmine:
`https://img.scryfall.com/cards/large/en/atq/82a.jpg?1509841014`
Battle Royal Box Set Mountain
`https://img.scryfall.com/cards/large/en/brb/122.jpg?1509843870`

I don't know what the number in the query string is for, possible just an internal tracking number, but the important fields are the last two. `https://img.scryfall.com/cards/<size>/en/<set code>/<collector number>.jpg?1509809953`
If there are any problems searching the internal LRRbot database for a card based on those two identifiers, you can also use them to get the full card info from scryfall as a JSON document (including the oracle text) by accessing `https://api.scryfall.com/cards/<set code>/<collector number>`
(ie `https://api.scryfall.com/cards/atq/82a`)

Do you think this will be a problem to add to LRRbot? My hope is to use this format for the Highlander tournament at the beginning of February.

**Comment by mrphlip** [comment]
The query string looks like a timestamp, it's probably just there to break through caching. Doesn't seem important.

The letters might be a little obnoxious... the way `atq/82a` and `atq/82b` etc are all just different arts of Strip Mine... but, say, `isd/90a` is Bloodline Keeper and `isd/90b` is Lord of Lineage... but I'm sure we can figure something out...

**Comment by mrphlip** [comment]
OK, a hiccup: for old sets from before collector numbers, the numbers don't exist in MTGJSON (because they don't exist in Gatherer). I'm guessing Scryfall made them up on their own. For those we'd need to pull from scryfall's API.

**Comment by mrphlip** [comment]
From further investigation... I tried to figure out if we can just guess the collector number order based off the card colour and name in the normal way, but there's too many weird exceptions and edge cases (most sets are in the normal order, but the Battle Royale Box is just in alpha order, but the Collector's Edition sets have the colours in _alphabetical_ order UBGRW except for some reason Badlands is grouped as a red card but the other lands are all at the end??? and I give up) so yeah, we'll just have to pull down the Scryfall data for the old sets and match the cards up.

**Comment by mrphlip** [comment]
OK, I have something in that I think should be working.

@paul-lrr When you test it out, some things worth testing:
* An old card from before they printed collector numbers - especially one with multiple arts, like the Antiquities Strip Mine you mentioned
* A double-faced card (both sides)
* One of the variant cards from Unstable - it should pull out the text for the same card you request, eg `ust/49c` should pull out Very Cryptic Command (C)

**Comment by paul-lrr** [comment]
Awesome! I know from experience that how the different card databases deal with the (plentiful) edge cases is a huge pain in the butt. I will try to test it ASAP.

As a side note, how difficult is it to add new card image formats for LRRBot to parse? I ask because there is a possibility for one more naming format :/ 

The above format is when I access scryfall images directly from the website, but for speed I might want to predownload the images locally. When I save scryfall images to the local computer, the filenames are in the format `<set code>-<collector number>-<card name>.jpg` where everything is lower case and the card name has been made into a slug. So *Elspeth, Sun’s Champion* would come through as `http://localhost/cards/ths-9-elspeth-sun-s-champion.jpg` It seems like you can just ignore the card name part of the file name an use the set code and number in the same way as above.

Sorry for all these different formats, I’m always trying to tweak/improve things as new possibilities become available and somethimes that has side effects in other areas.

**Comment by andreasots** [comment]
So now I think it's time to drop all these different input formats because the card recogniser/the overlay and the card viewer are too strongly coupled and every slight change in the card recogniser also requires us to make changes in the card viewer. Another flaw with the current implementation is PubNub. All PubNub does for us is add another dependency that just wastes processor and network resources doing nothing 99% of the time.

I propose that we switch to a HTTP POST request with just the information we need to uniquely identify a card.
Example payloads:
```json
{"name": "Strip Mine"}
{"name": "Adanto, the First Fort"}
{"name": "Very Cryptic Command", "variant": "c"}
{"multiverseid": 435173}
{"augment": "Half-Kitten, Half-", "host": "Adorable Kitten"}
```

**Comment by paul-lrr** [comment]
As is often the case with this sort of thing, the requirements have evolved over time and I am definitely not opposed  to switching to sending a json payload instead of the actual url. In addition to the payloads mentioned above, I guess we might also want something like:
`{"set":"atq","number":"82a"}`
Unless it would work better for me to do the scryfall API query on my side and always send the card name or multiverse id

**Comment by andreasots** [comment]
Then I want the request to mention that it's using the Scryfall nomenclature.

**Comment by paul-lrr** [comment]
Just did a quick test of the `https://img.scryfall.com/cards/large/en/lea/149.jpg?1509809953` style card links and they seem to work well. Nice work!

**Comment by mrphlip** [comment]
Something to keep an eye on: mtgjson/mtgjson#412 - will be useful if/when that lands.

**Comment by paul-lrr** [comment]
Quick question: Were you able to add the  `http://localhost/cards/ths-9-elspeth-sun-s-champion.jpg` format to lrrbot's cardviewer?

**Comment by paul-lrr** [comment]
just did a quick test and it looks like this format isn't working at the moment. However it looks like LRRBot has no problem interpreting the card name even when turned into a slug, so while `http://localhost/cards/ths-9-elspeth-sun-s-champion.jpg` doesn't work, `http://localhost/cards/ths-9_elspeth-sun-s-champion.jpg` with an underscore before the card name works fine. I will probably send the cards like that for the stream tonight. I would like to set up something with a JSON payload, as talked about above. Maybe I/we can work on that in the next little while

**Comment by andreasots** [comment]
> I would like to set up something with a JSON payload, as talked about above.

There's an unusually high chance of it happening in the next two weeks.

**Comment by andreasots** [comment]
I suspect that this has been resolved with the v2 of the API.
