### ISSUE TITLE
Total Subscriber count

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#445]
The `https://lrrbot.mrphlip.com/api/stormcount` endpoint provides the variously daily counts, but does LRRbot currently have a way to report the total number of subs/follows on the channel? We were thinking about revising the on screen storm count display to show the total number of subs for the channel as well as the daily totals. I think I can pull that number from the twitch API, but since the notifier is using LRRBot for everything else, I figured I would check if there is an easy way to do it through the LRRbot API.

**Comment by andreasots** [comment]
Nope, sorry.
