### ISSUE TITLE
Command cleanup

### ISSUE THREAD

**Issue by pterodactal666** [mrphlip/lrrbot#772]
I have noticed that there are a number of commands that are no longer relevant:

1. `calsurvey`: survey no longer exists, it now directs to the LRR main page.
2. `explain goc`: Games of Chance is no longer a stream. Same applies to `goc`
3. `explain jokefall`: Stolen Jokes hasn't been updated in over 2 years, so is it relevant?
4. `explain momir` and `momir`: This format doesn't seem to be played any more. Same applies to `explain phlottery` and `phlottery`

**Comment by amative1** [comment]
`calsurvey` and `explain goc` were removed at some point in the last year. `explain jokefall`, `explain momir`, and `explain phlottery` are set up as mod-only commands, so they are not able to be accessed. Issue can be closed.
