### ISSUE TITLE
Command multiple edit protection

### ISSUE THREAD

**Issue by mrphlip** [mrphlip/lrrbot#773]
The commands edit page needs some sort of protection against multiple people editing at once. Currently, if two people are editing at once, then one will overwrite the other's contributions with whatever data was on their page, loaded before their change, effectively undoing their changes.

Some options:
1. The blunt phpBB method - detect the conflict and refuse to save. Functional, but sucks if you've made a lot of changes and have to re-enter everything.
1. The MediaWiki method - detect the conflict and attempt to merge the changes, present a conflict resolution screen if both changes edited the same command. Neat, but complicated, lot of potential for a buggy implementation here.
1. Make all the changes immediate server-side, rather than client-side in JS, so each POST is editing a single command/response, not the whole list. Would substantially reduce the chance (and impact) of a conflict, but would make the page a lot more slow and clunky to use.

**Comment by AdmiralMemo** [comment]
I'm personally in favor of the MediaWiki method, but if that proves too difficult, then the blunt phpBB method would be favorable to making the page slower and clunkier.
