### ISSUE TITLE
Bugged Stats

### ISSUE THREAD

**Issue by AdmiralMemo** [mrphlip/lrrbot#83]
Alex changed the show tonight without changing the game (because the game wasn't on Twitch), so now we have some spurious stats for "Dark Souls" on "Let's Nope"

While you're in there, can you also fix the 4 "Unknown" show games?

Cities: Skylines
InsanZ - Retro Survival Horror
Mario Party 10
The World Ends With You

**Comment by AdmiralMemo** [comment]
Also Bloodborne on Heather's Handhelds, which I assume is not correct.

**Comment by andreasots** [comment]
* Deleted all games on Unknown.
* Deleted Dark Souls on Let's NOPE.
* Deleted Bloodborne on Heather's Handhelds. It had one death marked.

**Comment by andreasots** [comment]
[Chat discussion:](http://qrpth.eu/prism/log?start=1431414000.0&stop=1431500400.0#entry-2089743)
```
05:37 MrPhlip: I'm actually considering adding another mod page to the lrrbot website that'll let us mark game entries as "real"... so we should be able to more quickly look at all the new ones and flag ones that shouldn't be there
05:38 AdmiralMemo: That might be helpful. :-)
05:38 AdmiralMemo: But what defines "Real"?
05:39 MrPhlip: just that a mod has looked at it and said "yes, this is a real game entry that should exist, and not a mistake"
05:39 AdmiralMemo: I mean, "Windows 8.1" "Windows Notepad" and "Technical Difficulties" aren't actually games, but we purposely made them. :-)
05:39 MrPhlip: basically the idea is you'd go to the page, see a list of all the games that are new, and flag them as either "real" or "should be deleted"
05:39 AdmiralMemo: Oh OK. :-)
05:39 MrPhlip: "real" might not be the right word
05:39 MrPhlip: "verified" maybe
05:39 AdmiralMemo: Verified is good
05:40 MrPhlip: basically the idea being you'd only need to look at the new entries, not scroll through the whole list looking for problems
05:40 AdmiralMemo: OK, there are 1001 screams on "Star Control II"... I think Hosk or someone was having fun and forgot to reset that.
05:41 MrPhlip: I'm still edgy about adding the ability to actually *delete* the games via the website, at least unless I figure out a way to make a good undelete option... but it would also give a way to flag things that need to be deleted so that qrpth or I could go in and remove it, without having to post on the forums or github issues list or whatever
05:42 AdmiralMemo: Yeah, flagging is good. Deleting is not.
```

**Comment by d3fr0st** [comment]
Flagging would be good. It's probably much more user friendly to flag as incorrect instead of verified, unless someone takes charge of flagging stuff every couple of days.

I'm not great with website stuff but I'd like to try and get a page where mods can edit stats for a game easily without having to edit the json and restart the bot, and also not clog up the chat with changing show and game and all that jazz. That way we can easily edit smaller mistakes that haven't been handled by someone at the time, and get bigger stuff flagged for deletion.

**Comment by mrphlip** [comment]
The idea is that you would be flagging as *both*... game entries would either be "verified", "errors", or "unchecked". New game entries would be created as "unchecked" and would be set to one of the other two by a mod.

The idea being that flagging a game as an "error" would highlight it for one of us to delete it from the json, but flagging a game as "verified" is basically saying "I've already looked at this one and decided it's OK, so you don't need to show it to me again next time". So when you go looking for spurious game entries to flag, you only have to look through the *new* ones, not all every game entry that has ever been created (which is what Memo's had to do up to now).

**Comment by AdmiralMemo** [comment]
Beyond Good & Evil and Shin Megami Tensei: Devil Survivor 2 are currently in "Unknown"

**Comment by AdmiralMemo** [comment]
I added a bad game and it got stats before I could fix this. Please delete "We Made This" on Watch & Play.

**Comment by AdmiralMemo** [comment]
Several more stats have ended up bugged. Can we get the verification system online? Can I help?

**Comment by d3fr0st** [comment]
I'll get the bot to add a flag to the json. The flag is going to be (verified|error|unchecked) for every new game entries. File structure is going to go:
```json
"shows":{
   "(show)":{
      "(ID)":{
         "status": (verified|error|unchecked)
```
Website stuff is out of my wheelhouse sadly so I'll need some one to get that interface, in the meantime I'll add a command !status (status). Which will allow anyone with access to the json to quickly go through entries.

**Comment by d3fr0st** [comment]
I know @mrphlip and @qrpth are working from switching to a database system for file saving but that should be easier and quicker to implement for now.

**Comment by mrphlip** [comment]
Sorry about letting this get a bit behind...

Have purged:
6 "Unknown" entries
Portal (Gamehaus)
Civ V (GPLP)
Civ V (ToMS)
Fire Emblem: Awakening (Beej)
Fire Emblem: Awakening (IDDQDerp)
Far Cry 4 (CkPt)
Dark Shadows (ToMS)

**Comment by andreasots** [comment]
* Deleted Grand Theft Auto V on Unknown
* Deleted  Kingdoms of Amalur: Reckoning on Unknown. It had 2 deaths marked.

**Comment by andreasots** [comment]
* Deleted Dishonored on Unknown.
* Deleted Far Cry 4 on Unknown.
* Deleted Fire Emblem: Awakening on Unknown. It had 1 crow marked.
* Deleted Magic: The Gathering on Unknown. It had 1 flunge marked.
* Deleted Minecraft on Unknown. It had 1 diamond marked.
* Deleted Sid Meier's Civilization V: Brave New World on Unknown.

**Comment by AdmiralMemo** [comment]
Just dropping a few more that I noticed:

Sid Meier's Civilization V: Brave New World on GPLP
Portal 2 on CheckPoint Plus
Portal 2 on Heather's Handhelds
Chroma Squad on IDDQDerp
Baten Kaitos: Eternal Wings and the Lost Ocean on Things on My Stream
videojames on Video Games with Video James

Also, there are both Geoguessr and GeoGuessr on VGwVJ. The capital G is correct, so if the stats could be merged...

**Comment by andreasots** [comment]
* Deleted Sid Meier's Sid Meier's Civilization V: Brave New World by Sid Meyer on GPLP.
* Deleted Portal 2 on CheckPoint Plus. It had 1 flunge marked.
* Deleted Portal 2 on Heather's Handhelds.
* Deleted Chroma Squad on IDDQDerp.
* Deleted Baten Kaitos: Eternal Wings and the Lost Ocean on Things on My Stream.
* Deleted videojames on Video Games with Video James.
* Deleted Geoguessr on Video Games with Video James.

**Comment by AdmiralMemo** [comment]
Under Watch & Play, "Pahelika revelations 3D" should be fixed to "Pahelika revelations HD"

**Comment by andreasots** [comment]
* Deleted Rocket League on Unknown
* Renamed 'Pahelika revelations 3D' to 'Pahelika revelations HD'.

**Comment by AdmiralMemo** [comment]
Both GeoGuessr and Geoguessr have stats on A Swiftly Tilting Cameron so they need to be merged. 2 capital Gs is the correct spelling.
Also, "Magic Duels" on LRRMtG needs its name changed to "Magic Duels: Origins"

**Comment by AdmiralMemo** [comment]
Also, I don't think Alex ever played "Kingdoms of Amalur: Reckoning" on "Let's Nope"
Can someone check this? I think it might be a bugged stat from Adam's stream.

**Comment by d3fr0st** [comment]
I'll look into it, on a side note, steam classifies the game as magic duels, and magic duels is also a tagged game on twitch. With the plans of WotC for that game I feel it'd be smarter to keep it as Magic Duels.

**Comment by AdmiralMemo** [comment]
OK, then can we change the one on LRRMtG from "Magic Duels: Origins" to just "Magic Duels" for consistency?

**Comment by d3fr0st** [comment]
Also to double check is the rocket league entry in LRRMTG correct or was it an overlap with house of stark?

**Comment by AdmiralMemo** [comment]
I was there. Rocket League on LRRMtG is real. It was between draft rounds.
Crossing the Streams has both "Magic Duels" and "Magic Duels: Origins" as separate entries. There is only "Magic Duels" on LRRMtG.

**Comment by AdmiralMemo** [comment]
Also, it looks like someone "fixed" Cam's stream stats, but they fixed it to "Geoguessr" when it should be "GeoGuessr" instead.

**Comment by AdmiralMemo** [comment]
Alright, the chunguses decided to have a field day with the stats after the Let's Nope. I THINK I got rid of the supurrious stats, but I can't get rid of the game itself out of the database. Can Bad Mojo Redux on Unknown be removed from the database? Also, I think some of the stats on the Let's Nope version were messed up, but I'm not sure. I'm pretty sure we logged more than one scream. I'm pretty sure there WAS more than one scream at least.

**Comment by andreasots** [comment]
The chunguses (Usernameanniversary, RedHelveticaCake, vorox4, and mikmon) added stats only to Bad Mojo Redux on Unknown.
* Deleted Cards Against Humanity on Unknown
* Deleted Bad Mojo Redux on Unknown
* Deleted Creative on Unknown

**Comment by mrphlip** [comment]
I believe the plural is "chungodēs" ![Kappa](http://static-cdn.jtvnw.net/emoticons/v1/25/1.0)

**Comment by AdmiralMemo** [comment]
I don't think "Kingdoms of Amalur: Reckoning" was ever played on "Let's Nope"

**Comment by AdmiralMemo** [comment]
OK, W&P tonight got some wrong stats, as expected, so if someone could go through the log of times to check it out, that'd be great. While in there, it's been a while since things have been checked for correction, including the 2 noted above.

Meeuw and PepsiMan can be removed from Watch & Play (The correct spellings are Meeuuw and Pepsi Man, which are in the database already. I don't know if they can be merged.)

Also, there are now six games under "Unknown"
If you want to remove or merge them to the correct shows, whatever.

More wrong games:
SOMA on LRRMtG
Fire Emblem: Awakening on Crossing the Streams

Also, just for standardization:

Undo the rename of "Destiny" on several streams (It was named "Density" as a joke, but the joke is over.)
Rename "Minecraft: Super Hostile: Legendary" to "Minecraft: Super-Hostile: Legendary" (To conform with the existing "Super-Hostile")
Rename "Geoguessr" on ASTC to "GeoGuessr"

**Comment by andreasots** [comment]
* Deleted Kingdoms of Amalur: Reckoning on Let's NOPE. It had 6 deaths marked.
* Deleted XCOM: Enemy Within on Heather's Handhelds.
* Deleted Meeuw on Watch & Play. It had 2 pardonfucks marked.
* Deleted PepsiMan on Watch & Play. It had a pardonfuck marked.
* Renamed Pepsi Man to Pepsiman on Watch & Play. Added 1 pardonfuck.
* Deleted Hero Quest on Unknown.
* Deleted Undertale on Unknown. It had a pardonfuck marked.
* Deleted Super Mario Maker on Unknown.
* Deleted SOMA on Unknown.
* Deleted Pepsiman on Unknown.
* Deleted Shovel Knight on Unknown.
* Deleted Magic: The Gathering on Unknown. It had a flunge marked.
* Deleted SOMA on LRRMtG.
* Deleted Fire Emblem: Awakening on Crossing the Streams.
* Deleted Bloodborne on Crossing the Streams.
* Renamed Minecraft: Super Hostile: Legendary to Minecraft: Super-Hostile: Legendary on Crossing the Streams.
* Deleted display name for Destiny on Book of Passwords.
* Deleted display name for Destiny on House of Stark.
* Renamed Geoguessr to GeoGuessr on A Swiftly Tilting Cameron.

**Comment by AdmiralMemo** [comment]
*placeholder* on W&P should be Sukerunton To Koi Ni
Meeuw on W&P should be merged into Meeuuw

Somehow, we have 2 Pepsiman stats on W&P?

**Comment by AdmiralMemo** [comment]
Also, after watching a replay...

Duck Game on Crossing the Streams should be deleted.

**Comment by andreasots** [comment]
* Renamed \*placeholder\* on Watch & Play to Sukerunton To Koi Ni.
* Deleted Meeuw on Watch & Play.
* Deleted Bloodborne on Crossing the Streams.
* Deleted Duck Game on Crossing the Streams. It had a death marked.
* Deleted Mass Effect 2 on Crossing the Streams.
* Deleted Pepsiman on Watch & Play. It had 30 deaths, 6 pardonfucks and 4 screams marked.
* Added 30 deaths, 6 pardonfucks and 4 screams to Pepsiman on Watch & Play.

**Comment by andreasots** [comment]
* Deleted Dark Echo on Unknown.
* Deleted Mass Effect 2 on Unknown.
* Deleted Vagante on Unknown. It had one death marked.
* Deleted Bloodborne on Unknown. It was marked complete.

**Comment by AdmiralMemo** [comment]
Driver: San Fransisco on I, Horner can be deleted. (It's a typo.)

**Comment by andreasots** [comment]
* Deleted Driver: San Fransisco on I, Horner.

**Comment by AdmiralMemo** [comment]
Can we merge the MtGQuiz and MTGquiz stats on LRRMtG?

**Comment by andreasots** [comment]
* Deleted MTGquiz on LRRMtG. It had a death marked.
* Renamed MTGQuiz on LRRMtG to MtgQuiz.
* Added a death to MtgQuiz on LRRMtG.

**Comment by andreasots** [comment]
lrrtech should be named LRRtech. Creative and MtG Card Identifier on Things on My Stream should be deleted.

**Comment by AdmiralMemo** [comment]
There are both notepad and Notepad on IDDQDerp

We already had "Windows Notepad" on Let's Nope... Maybe standardize this?

**Comment by andreasots** [comment]
* Renamed lrrtech to LRRtech.
* Deleted MtG Card Identifier on Things on My Stream.
* Deleted Creative on Things on My Stream.
* Deleted notepad to Notepad on IDDQDerp.
* Renamed Windows Notepad to Notepad on Let's NOPE.

**Comment by andreasots** [comment]
* Deleted The Witness on Unknown.
* Deleted Dark Souls on Unknown.
* Deleted Duck Game on Unknown. It had a death marked.
* Deleted Board Games on Unknown. It had a bus-stop, a death, a diamond, and a flunge marked.
* Deleted Oxenfree on Unknown.
* Deleted Frederic: Evil Strikes Back on Unknown. It had a pardonfuck marked.
* Deleted The Aquatic Adventure of the Last Human on Unknown.

**Comment by andreasots** [comment]
* Deleted Fire Emblem (working title) on Unknown.
* Deleted Minecraft: Super-Hostile on Unknown. It had a death marked.
* Deleted The Solus Project on Unknown.

**Comment by AdmiralMemo** [comment]
We have both Superhot and SuperHot under IDDQDerp. The one with intercaps is from before it was fully released and before it went on Twitch. We didn't know the accurate capitalization then.

Can we merge them both into Superhot? SuperHot has 7 deaths, 2 bad ratings, and 23 good ratings.

**Comment by andreasots** [comment]
* Deleted SuperHot on IDDQDerp. It had 7 deaths marked.
* Added 7 deaths to Superhot on IDDQDerp.

**Comment by AdmiralMemo** [comment]
Delete Hyrule Warriors on IDDQDerp
It was due to an override on Heather's Handhelds not being turned off.
Also, due to !game refresh not working.

**Comment by andreasots** [comment]
> Also, due to !game refresh not working.

`!game refresh` was working.

* Deleted Hyrule Warriors on IDDQDerp.

**Comment by AdmiralMemo** [comment]
Also... Should I start a new thread for quote context or just use this?

"Magic: The Gathering on None" is the context for quotes 2266, 2267, and 2268, when it should be "Magic: The Gathering Online on LRRMtG"

(Of note, the bot had just rebooted at the time.)

**Comment by bunglelow** [comment]
I wonder if its worth adding a quote management for mods that allows editing of quotes/contexts/meta data rather than bloating the modquote command. Probably worth a new issue if we want to extend the features

**Comment by andreasots** [comment]
Quote management interface is part of #165.

* Set show on quotes #​2266, #​2267, #​2268 to LRRMtG.

**Comment by AdmiralMemo** [comment]
Due to no Mod being available to change the game and the game not being on Twitch, "Games + Demos" on i, Horner needs to be migrated to "Knee Surgery Simulator"

(I don't think a name change is in order in this case, as they'd likely use that "game" on Twitch for any future games not in the database.)

Also, I've done a name override as a temporary measure, but "Memories of a Broken Dimension" should be updated to "Memory of a Broken Dimension" on i, Horner.

**Comment by AdmiralMemo** [comment]
We've got 4 games on "Unknown" currently:

Dark Souls
Hyper Light Drifter
Magic: The Gathering
Samorost 3 Concept Art

Also, did Paul ever play Watch Dogs on ToMS or is that a bug?

Beej's Backlog has "something with a child king?" which I assume was a joke?

Heather's Handhels has both "PaRappa The Rapper" and "PaRappa the Rapper" and I think the second one is the correct capitalization.

**Comment by AdmiralMemo** [comment]
We've got both "Dark Souls 3" and "Dark Souls III" on both ASTC and Let's Nope, and I believe the second one is the real one.

AFK has both "Citadel" and "Citadels" and I have no clue.

"Pocket Card Jockey" on IDDQDerp, which I believe is a hold-over from Heather's Handhelds prior.

There's Dark Souls III on VGwVJ. I don't know if James played that or if it was a hold-over from ASTC.

On Watch & Play, there's both HARDtime... and Hard Time (the second set to display HARDtime...). I believe the second is what's in the Twitch database. The first is how it's actually displayed in the game.

Now, the complete list on Unknown is:

Dark Souls	
Demon's Souls	
Doom	
Dungeons & Dragons: The Legend of Drizzt	
Half-Life 2	
Hyper Light Drifter	
Magic: The Gathering	
Samorost 3 Concept Art	
Space Channel 5: Part 2

Demon's Souls was Let's Nope
Doom was Let's Nope
D&D was AFK
Half-Life 2 was IDDQDerp
Samorost 3 Concept Art was IDDQDerp
I assume Space Channel 5: Part 2 was Rhythm Tuesday, for whatever that's listed under.

Regarding editing quote references...

2556: Should be CTS not W&P
2535 and 2536: Should be CheckPoint Plus on CheckPoint Plus
2521: Should be CheckPoint Plus

**Comment by RebelliousUno** [comment]
Fwiw James did play ds3

**Comment by AdmiralMemo** [comment]
W&P has both Silver Bullet: Prometheus and Silver Bullet: The Prometheus, and I have no idea which is the real one.
I've got a display that overrides Desert Thunder with Desert Thunder: Strike Force, but I'm hoping it could be actually fixed at some point.

**Comment by AdmiralMemo** [comment]
And now we need to delete "Anime Was a Mistake" on "Matters of Import" because Chat misled me on the name of the game.

**Comment by AdmiralMemo** [comment]
Quotes 2897 and 2898 should be on "Mahou Kishi Rayearth on Matters of Import" instead of "Inside on New Day Tewsday"
