### ISSUE TITLE
Chat logs: :/ in URLs is rendered as an emote

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#87]
Example: http://qrpth.eu/prism/log?start=1431785340.0&stop=1431785400.0

**Comment by mrphlip** [comment]
http://qrpth.eu/prism/log?start=1431955600&stop=1431955960

**Comment by andreasots** [comment]
Regression: https://qrpth.eu/prism/log?start=1455468500&stop=1455468501
