### ISSUE TITLE
extracting a random word from the last x lines of chat

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#906]
Not *totally* sure if this would need to be done through LRRbot, but we were talking about an idea for a future LRL bit today and I wanted to check the feasibility. There is an improv game that involves bringing up an audience member to supply single words as needed, kind of like a on-the-fly mad libs. 
Eg. Let's to to the --park--! We'll take the --hair-- car and pickup a --missile-- on the way etc.

We were thinking about setting up something that could extract a random word from recent chat lines whenever we push a button. My immediate thought was, in order to make it a *little* more coherent, it would be cool to be able to ask for a particular *type* of word. Have different buttons for verb, noun, adjective, etc. 

I know there are existing libraries that to parse text into different parts of speech, so it *seems* doable, but I wanted to get your thoughts.

**Comment by paul-lrr** [comment]
This is **not for today**, btw. We were just discussing potential future LRL bits

**Comment by andreasots** [comment]
Right now this could be done by scraping the chat logs at https://qrpth.eu/prism/. So something like this: 
```js
const { JSDOM } = require('jsdom'); // jsdom ^16.2.0
const https = require('https');
const pos = require('pos'); // pos ^0.4.2const stop = Date.now() / 1000;
const start = stop - 600;https.get(`https://qrpth.eu/prism/log?start=${start}&stop=${stop}`, (res) => {
    let data = '';
    res.on('data', chunk => data += chunk);
    res.on('end', () => {
        const lexer = new pos.Lexer();
        const tagger = new pos.Tagger();
        const extractedWords = {};
        const dom = new JSDOM(data);
        for (const [i, msg] of dom.window.document.querySelectorAll('span.message').entries()) {
            for (const [word, tag] of tagger.tag(lexer.lex(msg.textContent))) {
                extractedWords[tag] = extractedWords[tag] || [];
                extractedWords[tag].push(word);
            }
        }
        // The tags are described here: https://github.com/dariusk/pos-js/blob/master/README.md
        console.log('Noun:', extractedWords.NN[Math.floor(extractedWords.NN.length * Math.random())]);
        console.log('Verb:', extractedWords.VB[Math.floor(extractedWords.VB.length * Math.random())]);
        console.log('Adjective:', extractedWords.JJ[Math.floor(extractedWords.JJ.length * Math.random())]);
    });
});
```

Closing because a) there is a semi-reasonable alternative and b) it's not clear that it would ever get used, like `!game good`/`!game bad`.
