### ISSUE TITLE
Using lrrbot for sub notifications

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#92]
We currently use tnotifier (tnotifier.net) to run the popup sub notifications. The system works pretty well, but, despite assurance that the feature is in development, it has never worked for resubs. It turns out that our viewers are really loyal (Yay!) which means that most subs are resubs and only a few actually show up on the stream. Other freely available subscriber notification systems I have found have similar problems or don't allow enough customization. I realized that LRRbot is already doing sub and resub tracking with its welcome messages and the notifications page (http://lrrbot.qrpth.eu/notifications). If LRRbot could have an api endpoint that returned all the subs in the last x minutes or maybe the last x subs, along with how many months they have subscribed for, then it should be pretty straight forward for me to make a notifier plugin for xsplit that checks the list every minute, removes duplicates, and then fires a notification  for any new subscribers or resubs.

Ideally the endpoint would return a JSON file something like this:
`{{"drmcgoodtimes",3},{"aussz",6},{"mrphlip",18},{"newguy",0}}`

Does this make sense and do you think this is something that LRRbot could do without too much trouble? As I said, I was thinking that most of the work of actually collecting the notifications has already been done for the welcome and notifications page.

-Paul

**Comment by mrphlip** [comment]
We actually already have this, the notifications page itself uses it to display live updates (my theory was the host could leave the updates page open on another screen, and if they miss a sub they could quickly look over to see who they missed).

http://lrrbot.mrphlip.com/notifications/updates?after=0 - Every notification in the last 2 days, the same as shown on the notifications page. You can then put the "key" value of the last one as the "after" param to only get the new ones.

Alternatively, http://lrrbot.mrphlip.com/notifications/events - the same data, as an SSE stream. If you're able to connect to this from whatever xsplit plugins are written in, you should be able to get direct push notifications with every sub, to show the pop-up immediately, rather than polling.

Have a look at https://github.com/mrphlip/lrrbot/blob/master/www/static/notifications to see how the LRRbot site does it.

**Comment by andreasots** [comment]
There are two endpoints that the website uses:

1. [SSE](https://en.wikipedia.org/wiki/Server-sent_events) endpoint for recent browsers: http://lrrbot.mrphlip.com/notifications/events.
2. AJAX endpoint for ancient browsers: http://lrrbot.mrphlip.com/notifications/updates?after=0. Only entries with the `key` field larger than the `after` parameter will be returned.

Both yield entries like this:
```
{
      "avatar": null,
      "channel": "#loadingreadyrun",
      "key": 5202,
      "message": "clockwork_penguin just subscribed!",
      "monthcount": 9,
      "time": 1433879849.536257,
      "user": "clockwork_penguin"
}
```

You can find example Javascript code in http://lrrbot.mrphlip.com/static/notifications.js marked `SSE code` and `AJAX fallback`.

**Comment by mrphlip** [comment]
Ha, I win!

**Comment by andreasots** [comment]
<incoherent gibberish>

**Comment by paul-lrr** [comment]
So fancy! You guys are way ahead of what I was thinking :)

I will look at the sample code and do some messing around in xsplit and see what I can come up with.

**Comment by paul-lrr** [comment]
Is there any way to get lrrbot to manually fire a test notification? I have a version of the notifier up and running but there seem to be some problems with missed or delayed notifications. I'm assuming that it is related to how xsplit's html/JavaScript plugin interface works and it would make testing much easier if I didn't have to wait for a legit subscription before knowing if it is fixed.

**Comment by andreasots** [comment]
Do a POST request on http://lrrbot.mrphlip.com/notifications/newmessage with `test` set to `true`.
Note that the `time` key is named `eventtime`, everything else has the same name.

Example `curl` command:
```
curl http://lrrbot.mrphlip.com/notifications/newmessage --data "test=true&apipass=[DICKBUTT]&message=test+just+subscribed\!&channel=#loadingreadyrun&user=test&eventtime=1434015411"
```

**Comment by paul-lrr** [comment]
Awesome! Just so I am clear, aside from the overlay, where will these test notifications show up? Will they appear in the chat and on the LRRbot notifications page? In any case, I will try to restrict my testing to when the stream is offline to minimize any confusion :)

**Comment by andreasots** [comment]
The test notifications will only show up in the feeds. The web page filters out test notifications and the bot isn't using the notifications because it's generating them.
