### ISSUE TITLE
LRRbot twitch account Permissions

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#921]
Does LRRbot have sufficient permissions on the LoadingReadyRun twitch account to:
- update the game and channel title
- run an ad break
- set the go live notification?

Wondering because as more crew are streaming from home, twitch's 2FA is causing some issues with people not easily logging in to change the stream info and now that we will be running more ads, they need to login even more (instead of just using the stream key). I was thinking that, if LRRbot is authorized, the changes could be made via whispered commands in the chat

**Comment by phil-bradbury** [comment]
I don't believe lrrbot is currently an "editor", but if we get that permission set up, then we'd have access to:
* Ad breaks
* Raids/hosting
* Changing stream title, current game, stream delay
* Enable or disable the "channel feed" which I presume is the go-live notification?
* Join/leave communities
* Add markers to vods
* Create Collections (a feature I'm not too familiar with, looks like some sort of vod playlist?)
* Upload and manage videos

A lot of these we wouldn't need, but that's everything I can find in the API docs and the chat command listings. We can pick the parts of this we want and expose them as mod-only (or even broadcaster-only) chat commands.

There are other things that being an editor gives you access to, like creating highlights, but that doesn't have an API.

**Comment by RebelliousUno** [comment]
Iirc lrrbot is an editor as we can use it to host.

**Comment by d3fr0st** [comment]
It is

**Comment by d3fr0st** [comment]
Though if the problem is access to the dashboard giving the crew editor power would fix that, as they'd be able to access it on their own accounts

**Comment by paul-lrr** [comment]
> Though if the problem is access to the dashboard giving the crew editor power would fix that, as they'd be able to access it on their own accounts

oh wow, I totally forgot that was a thing. That is WAY easier. Score one for twitch actually having a feature that I need 😏 

Thanks for the tip!
