### ISSUE TITLE
Founders aren't considered subscribers

### ISSUE THREAD

**Issue by mas90** [mrphlip/lrrbot#928]
Twitch doesn't set the 'subscriber' tag on users who have founder badges (i.e. the first 25 subs to the channel).  Twitch doesn't consider this to be a bug: https://discuss.dev.twitch.tv/t/founders-are-not-marked-as-subscriber-in-irc/22792

So, for example, LRRbot doesn't consider me (Twitch user "malc") to be a subscriber (I have no access to sub-only commands) even though I currently am subscribed to loadingreadyrun.

**Comment by mrphlip** [comment]
What the heck, Twitch, how is "just use the badges" a suggestion, if you _also don't include the subscriber badge_ for founders?

```
@badge-info=founder/58;badges=founder/0;color=#0000FF;display-name=malc;emotes=;flags=;id=78a3fd29-41ba-49e1-8a57-adc8f632648b;mod=0;room-id=27132299;subscriber=0;tmi-sent-ts=1586175178248;turbo=0;user-id=26261124;user-type= :malc!malc@malc.tmi.twitch.tv PRIVMSG #loadingreadyrun :!badadvice
```

I'm pretty sure there's currently no way to tell the difference between a founder who is currently subscribed and a founder whose subscription has lapsed.

I mean, it's not a big deal just giving founders access to sub-only commands, regardless... but the pedant in me chafes...
