### ISSUE TITLE
whispering !next to new chat users

### ISSUE THREAD

**Issue by paul-lrr** [mrphlip/lrrbot#98]
Twitch just recently added whispering functionality to the chat system. When you type `/w <username> <message>` into the chat, it sends a message to only that user. Would it be possible to have LRRbot /w the next stream info to each user as they enter the chat? If it _is_ possible, do you think it would actually be helpful? Maybe it should only do it if there isn't a stream currently running.

**Comment by d3fr0st** [comment]
I actually tried a simple command to test whispering right when it was announced. /w <user> "message" in simple chat command coming from the bot didn't actually even show in chat. I could look into it as it would clear the chat, mostly right before shows or when the a show is late. My only concern is that /w isn't actually handled in a channel chat (You can whisper to user not in the same channel as you are and they will get it) and it might require some fiddling around... As a side note the bot also can't receive whispers.

**Comment by paul-lrr** [comment]
Hmmm. That is true, I guess the multichannel whisper thing does indicate that there is something fancy going on. In doing some more research, I see other bot developers had similar questions and the answer seems to be "not possible". Le sigh....

**Comment by andreasots** [comment]
[Whispering "documentation"](http://discuss.dev.twitch.tv/t/whispers-on-irc/2459/3):
* Connect to a group chat server. Currently `199.9.253.119` or `199.9.253.120`. The servers are listed in `https://chatdepot.twitch.tv/room_memberships?oauth_token=[DICKBUTT]`.
* Request `twitch.tv/commands` capability.
* Sending: `PRIVMSG #jtv :/w <user> <message>`
* Receiving: `WHISPER <user> :<message>`.

There's a warning that it will change soon to not be over IRC.

**Comment by andreasots** [comment]
It would be best if this was opt-in so people not familiar with LRRbot don't get confused and/or report LRRbot for spam.

**Comment by mrphlip** [comment]
... Well. That sounds unnecessarily convoluted.

I had considered making it so that people could whisper commands to the bot, and get responses whispered back (pretty common practice for irc bots, and something I already made lrrbot do by force of habit on the offchance that twitch ever supported IRC-style /msg commands)... but running a second connection just to receive them might be overkill...

I mean, it's probably doable, but I don't think it's worth the effort. Especially since the protocol is still in flux.

**Comment by paul-lrr** [comment]
From the twitch staff in that same thread:
>We purposely made whispers convoluted for IRC integration because we didn't want users and bot developers to become reliant on receiving user-to-user messages via IRC. We have plans to stop using TMI to send user-to-user messages and instead use a new system (and protocol) entirely. When will this happen? Hopefully in the few months.

So it being unnecessarily convoluted is actually a **feature** >_<

In any case, it probably isn't worth spending effort on right now. Maybe when they get this "new protocol" set up it will be easier.
